### ISSUE TITLE
Can't draw on map 

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/intergeo-maps#66] opened 2017-07-26 04:13 UTC
@selul after drawing a shape and saving it's gone from the map: http://prntscr.com/g0co0g

**Comment by UVLabs** [comment] 2017-08-16 18:54
+1 this relates to this @contactashish13 https://secure.helpscout.net/conversation/412886804/140263/

**Comment by contactashish13** [comment] 2017-08-17 06:33
@selul I've created a PR against production (without running phpcs as it was returning a lot of errors): https://github.com/Codeinwp/intergeo-maps/pull/68

**Comment by UVLabs** [comment] 2017-08-24 00:38
+1

**Comment by contactashish13** [comment] 2018-06-05 03:44
@UVLabs have you tested this recently? I cannot reproduce this issue. Please share a video so that I can understand the issue better.

**Comment by rodica-andronache** [comment] 2018-06-06 09:06
@contactashish13 I don't know how this drawing works. Is it from this options https://prnt.sc/jri8nb ? How to make them visible? Thanks :D

**Comment by contactashish13** [comment] 2018-06-06 12:57
@rodica-andronache I see what you mean. Those drawing tools appear when Pro is activated.

![image](https://user-images.githubusercontent.com/12953439/41039475-2b15a38e-69b7-11e8-9dd8-21ed02cae79e.png)

But maybe those accordions on the RHS should not appear when only lite is activated. Do you want to create a new issue for that?

**Comment by rodica-andronache** [comment] 2018-06-06 14:05
@contactashish13 yes, if those options are available just in pro, they shouldn't appear at all in lite. You don't have to create a new issue, you can work on this one I think.
And in pro, everything is working well? maybe @UVLabs can tell us more :)

**Comment by contactashish13** [comment] 2018-06-07 03:46
@rodica-andronache I'll close this issue in favor of #48 so that all changes can go as one PR.

**Closed as completed by contactashish13** 2018-06-07 03:46 UTC
