### ISSUE TITLE
Shortcode address doesn't seem to be working

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/intergeo-maps#65] opened 2017-07-16 03:37 UTC
I've tried adding this: 

`[intergeo zoom="12" width="50%" height="400px" style="border: 3px solid red; margin: 0 auto;"]Central Park New York, NY 10024, USA[/intergeo]`

and this

`[intergeo zoom="12" width="50%" height="400px" style="border: 3px solid red; margin: 0 auto;"]Central Park, NY[/intergeo]`

And neither show up on the map, the map still centers to Munich and no marker appears in New York on the map, so it seems like something is not right with the address system, a user also wanted to know if there's any way to add multiple markers to the map like on the UI builder, but straight inside the shortcode

@selul

**Comment by contactashish13** [comment] 2018-06-05 03:37
@UVLabs I was able to reproduce this issue because I forgot my API key. You have to ensure that your API key supports the geolocation API. If it does not, it will not geocode the address. All errors pertaining to google maps are shown in the developer console. You will see the error for this issue in the console as well.

@rodica-andronache we don't have support for multiple addresses. Does this need to be added?

**Comment by rodica-andronache** [comment] 2018-06-06 12:10
@contactashish13 and how do you make sure that the API key supports the geolocation API? Is there something to do? Because if there is, we can add a doc or something.
I tried with my API key and indeed is not working, but I don't understand how I could make it work

**Comment by contactashish13** [comment] 2018-06-06 12:51
@rodica-andronache there is no way to make sure. We call the API and the API throws an error in the JS console. That is the only way of making sure that the key supports the API. In fact, that is how I found out as well.

You may want to look at updating the video in the plugin that shows how to get the API key. The process has become a little more complicated now as you have to enable specific APIs.

**Comment by rodica-andronache** [comment] 2018-06-06 14:14
yes, I was thinking about that.
@dascalescuro it would be possible to update this video https://www.youtube.com/watch?v=rqucit5YHNk&t=54s ? Like Ash said the process to get your API key changed, and it's not easy to follow.
@contactashish13 isn't something that should be done in the plugin? maybe you can investigate a bit? https://developers.google.com/maps/documentation/geolocation/intro

**Comment by dascalescuro** [comment] 2018-06-06 14:39
I am trying to look at the new process.
Does this one require payment? It is really weird...

**Comment by rodica-andronache** [comment] 2018-06-06 14:55
from what I've seen, no. If you start from the link suggested in the video console.developers.google.com/apis/library

**Comment by contactashish13** [comment] 2018-06-07 03:45
@rodica-andronache I'll close this issue in favor of #48 so that all changes can go as one PR.

**Closed as completed by contactashish13** 2018-06-07 03:45 UTC
